### ISSUE TITLE
Semantic segmentation source

### ISSUE THREAD

**Issue by myth01** [clovaai/overhaul-distillation#1]
Hello,

When do you plan to release source code corresponding to section 4.4 Semantic Segmentation in the paper?

Thanks!

**Comment by bhheo** [comment]
Hello,

In case of detection and segmentation, the distillation part is almost identical to ImageNet code. But, the base training code is quiet complicated and there are a lot of things to clean up.
Perhaps the release date will be after the ICCV 2019 conference or after the CVPR 2020 submission deadline.

**Comment by bhheo** [comment]
Segmentation codes were released today.
So, this issue will be closed.
