### ISSUE TITLE
Implementation of other methods

### ISSUE THREAD

**Issue by GUOShuxuan** [clovaai/overhaul-distillation#17]
Hi, your work is very interesting and useful to the community. 

Would you mind also releasing your implementation of other methods which would be very helpful?

**Comment by bhheo** [comment]
I'm sorry but, I didn't clean up codes about other method. It's really a mess.
So, I don't want to release that code.

If you want to get codes for other method, this repo will help you.
https://github.com/HobbitLong/RepDistiller
I'm not involved with this repo, but it's well written and includes many distillation methods.
Just remember that this repo is basically implemented without KD, so you should add KD loss to other methods for fair comparison.

**Comment by GUOShuxuan** [comment]
Thanks. 

Cheers
