### ISSUE TITLE
question about get_margin_from_BN function

### ISSUE THREAD

**Issue by jiseo** [clovaai/overhaul-distillation#19]
hi, I have a question about get_margin_from_BN function.
in this method, you use like the below.
   std = bn.weight.data
   mean = bn.bias.data

But, as I know, bn.weight and bn.bias mean respectively gamma and beta. 
there are bn.running_mean and bn.running_var for mean and variance.
could you explain why you use gamma as std and bias as mean?

**Comment by bhheo** [comment]
Hi.

Running mean and var represent statiatics **before** batch-norm.
But, I want statistics **after** batch-norm which is same as stats before relu.
Output of batch-norm follows normal distribution, thus `mean = 0, std=1`.
But, gamma and beta change it to `mean = beta, std = gamma`.
So, I use gamma and beta for margin calculation.
