### ISSUE TITLE
detection?

### ISSUE THREAD

**Issue by jianbaba** [clovaai/overhaul-distillation#20]
hello,Hello author, thank you very much for your project. Is there any open source code for detection?

**Comment by bhheo** [comment]
Hi
I'm sorry but there are no detection code.
Because our experiments are based on private detection code, I can't release it.

**Comment by CPFLAME** [comment]
@bhheo 
can you share  how much detection mAP improvement？

**Comment by bhheo** [comment]
@CPFLAME 
Hi, you can find it on Table 5 of my paper
![image](https://user-images.githubusercontent.com/8871141/103972711-e3085480-51b0-11eb-8820-a57691d18836.png)
