### ISSUE TITLE
The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable.

### ISSUE THREAD

**Issue by musab-r** [clovaai/overhaul-distillation#26]
After running the command for CIFAR-100 i got this here, full error message is here:

`RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.`

How to resolve it?

**Comment by bhheo** [comment]
I don't know about this error.

It might be related with PyTorch on Windows or macOS
https://github.com/pytorch/pytorch/issues/5858
Since my code is implemented based on ubuntu, I recommend to use PyTorch on ubuntu
