### ISSUE TITLE
loss 계산하는 과정에서 1000 으로 나누어주는 부분에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by cbpark-nota** [clovaai/overhaul-distillation#27]
안녕하세요, 코드를 보다 궁금하여 질문을 남깁니다.

https://github.com/clovaai/overhaul-distillation/blob/76344a84a7ce23c894f41a2e05b866c9b73fd85a/CIFAR-100/train_with_distillation.py#L91

위 부분에서 왜 loss 를 1000 으로 나누어주는지 알 수 있을까요?
논문에서 제가 놓친 부분이 있는것 같습니다.
감사합니다.

**Comment by bhheo** [comment]
안녕하세요.

논문의 Equation (6) 의 parameter alpha의 값이 (1/1000) 이므로 / 1000 이 들어갑니다.
![image](https://user-images.githubusercontent.com/8871141/95355705-cf72f680-0900-11eb-8f31-ed967e37e4e4.png)

**Comment by cbpark-nota** [comment]
답변 감사합니다.
