### ISSUE TITLE
how to compute margin from BN statistics?

### ISSUE THREAD

**Issue by Pixie8888** [clovaai/overhaul-distillation#29]
Hi,
I still can't understand how to compute margin from BN statistics after reading the code. Can you explain a little bit (why you compute cdf?)
![image](https://user-images.githubusercontent.com/72333326/101281806-50207700-380c-11eb-92c3-7a2ab3f5352f.png)

**Comment by bhheo** [comment]
Hi

I assume that the features after BN is Gaussian distribution, and calculates the margin based on expectation values of Gaussian distribution. 
You can find more details on Appendix A of my paper (https://arxiv.org/pdf/1904.01866.pdf)
I hope it helps you understand the formular.
