### ISSUE TITLE
Question about how to calculate m in margin ReLU

### ISSUE THREAD

**Issue by Nusselder9** [clovaai/overhaul-distillation#31]
Hi,
Thanks for your cool work. It obtains the best performace on Res50 for all feature-distillation works.

I have a question about how to calculate m in margin ReLU. 

Actually, I noticed that you implement it as `margin.append(- s * math.exp(- (m / s) ** 2 / 2) / math.sqrt(2 * math.pi) / norm.cdf(-m / s) + m)`  [at here](https://github.com/clovaai/overhaul-distillation/blob/76344a84a7ce23c894f41a2e05b866c9b73fd85a/ImageNet/distiller.py#L37). Can you give me some ideas about what does it mean?

**Comment by bhheo** [comment]
Hi

I assume that the features after BN is Gaussian distribution, and calculates the expectation of negative values on Gaussian distribution.
You can find more details on Appendix A of my paper (https://arxiv.org/pdf/1904.01866.pdf)
I hope it helps you understand the formula.

**Comment by Nusselder9** [comment]
Thanks!
