### ISSUE TITLE
About the margin

### ISSUE THREAD

**Issue by Fangkang515** [clovaai/overhaul-distillation#32]
Thanks for your code!
In the paper, the authors say:" the margin value defined as the channel-by-channel expectation value of the negative response", as follows:
![image](https://user-images.githubusercontent.com/34268707/104428920-ff94fa00-55bf-11eb-9ddc-34efa05adbf4.png)
. 
And, in this code, the margin is set by:
![image](https://user-images.githubusercontent.com/34268707/104429358-7d590580-55c0-11eb-961b-580032065dfa.png)
The margin in this code seems to be set to std. Are they equivalent？

**Comment by bhheo** [comment]
Hi

You can find more details on Appendix A of my paper (https://arxiv.org/pdf/1904.01866.pdf)
It is a result of expectation operation over negative area of distribution.
![image](https://user-images.githubusercontent.com/8871141/104430419-fc067080-55c9-11eb-9f18-b493df1e473e.png)
