### ISSUE TITLE
A new implementation for overhual  distillation

### ISSUE THREAD

**Issue by zjykzj** [clovaai/overhaul-distillation#36]
@ClovaAIAdmin Thank you for sharing this nice work

Based on torchvision's ResNet/MobileNet and Distiller you realized, I make a new implementation [ZJCV/overhaul](https://github.com/ZJCV/overhaul)

I have done some experiments, and can really improve performance. Using ResNet152 (teacher) and ResNet50 (student), the performance of students' network even surpasses that of teachers' network.

ResNet50 | 83.290 | 96.630 | ResNet152 | 85.660 | 97.590 | CIFAR100 | 2.0 | 86.080 | 97.350
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by bhheo** [comment]
@zjykzj Thank you for your effort in implementation.

It looks well-organized implementation with excellent results.
It will help many researchers to compare their new distillation method with ours.

I'm sorry for the late message.
Thank you so much for sharing your new implementation.

Best
Byeongho Heo
