### ISSUE TITLE
ImageNet Trained model

### ISSUE THREAD

**Issue by gadhane** [clovaai/overhaul-distillation#39]
Hi,

Would it be appropriate to ask for the trained distillation model on ImageNet? It would be greatly appreciated and a million help if you could share the trained distillation models on imageNet for download.

thank you!

**Comment by bhheo** [comment]
Hi

I'm sorry but I can't find the ImageNet models in my storage.
It might be removed because of a storage issue.
Sorry

**Comment by gadhane** [comment]
Thank you for your reply, and you don't have to be sorry. :)
