### ISSUE TITLE
ResNet architecture

### ISSUE THREAD

**Issue by mileyan** [clovaai/overhaul-distillation#5]
Thanks for your great work!

I am a little bit confusing about the resnet architecture. 
https://github.com/clovaai/overhaul-distillation/blob/master/ImageNet/models/ResNet.py#L55
The last ReLU has been removed from all res-blocks, not just the last res-block in each res-layer. Will this hurt model performance? Also, have you retrained the model?

Thanks for your help.

**Comment by bhheo** [comment]
Hi

As you mentioned, I removed last ReLU for pre-ReLU feature.

https://github.com/clovaai/overhaul-distillation/blob/f5b9929f5b29806540ecaf5b83435ad594071d17/ImageNet/models/ResNet.py#L94-L95

Instead, I added ReLU to the front of ResBlock.

https://github.com/clovaai/overhaul-distillation/blob/f5b9929f5b29806540ecaf5b83435ad594071d17/ImageNet/models/ResNet.py#L40-L42

The last ReLU is just moved to the first ReLU of ResBlock.

And I also added a ReLU for last layer block.

- My version
https://github.com/clovaai/overhaul-distillation/blob/f5b9929f5b29806540ecaf5b83435ad594071d17/ImageNet/models/ResNet.py#L141-L156

- [TorchVision](https://github.com/pytorch/vision/blob/09823951fec09215f9efc5d5d31456763da5ae04/torchvision/models/resnet.py#L197-L212)
```Python
    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)

        return x
```

As a result, our network is the same as the original.
My code loads parameters from official PyTorch model.

https://github.com/clovaai/overhaul-distillation/blob/f5b9929f5b29806540ecaf5b83435ad594071d17/ImageNet/models/ResNet.py#L12-L18

But, performance is not changed.

**Comment by mileyan** [comment]
It is very clear. Thanks for your help.
