### ISSUE TITLE
question abount margin seting

### ISSUE THREAD

**Issue by SaintLogos1234** [clovaai/overhaul-distillation#6]
Hi, I look at the code you provided， i can't understand margin setting, I read get_margin_from_BN,
I can't understand this code: margin.append(- s * math.exp(- (m / s) ** 2 / 2) / math.sqrt(2 * math.pi) / norm.cdf(-m / s) + m), can you explain to me what it does and why does it, Thank you very much;

**Comment by bhheo** [comment]
Hi

The code about margin value is described in Appendix A of my [paper](https://arxiv.org/abs/1904.01866)

It is results of integral over gaussian distribution.
To calculate expectation of negative feature values.

If you want more than Appendix A, please give me additional comment.

**Comment by hwcasus** [comment]
Hi, 
I notice that in you paper, you mention that 
>margin can be obtained directly during training
Does this mean that I can inference every training image with a well-trained teacher model and simply calculate the average of all negative value in certain channel?

**Comment by winycg** [comment]
hi，I would like to know why if norm.cdf(-m / s) < 0.001， then margin=-3 * s. Thanks!

**Comment by bhheo** [comment]
@winycg
Hi

That line prevents overflow of `1/norm.cdf(-m / s)` in following code
https://github.com/clovaai/overhaul-distillation/blob/392a006560c2ab3aca8bb8fc7b1bf826298d9fd6/ImageNet/distiller.py#L37

When response distribution is heavily biased to positive, negative probability is too small to calculate margin without overflow.
In that case, I set the value (-3s) as margin instead.
When this value is used, negative probability is quiet small (less than 0.1%).
Therefore, margin value is rarely used and not important.
So, I just pick up 3 sigma for that case.
