### ISSUE TITLE
Question about the change of the size of feature

### ISSUE THREAD

**Issue by Ernie1** [clovaai/overhaul-distillation#8]
Thanks for your excellent job! In Appendix A of your paper, it says
> When one moves from the top layer to the bottom layer, the total size of the feature is increased by twice the amount as spatial resolution increases.

Should it be "decrease" rather than "increase"?

**Comment by bhheo** [comment]
Hi

I'm sorry for the poor explanation of that part.
But, "increase" is my intention.

For example, in ResNet 50, there are features as follows

|                  | Layer 4 (top) |     Layer 3    |    Layer 2    | Layer 1 (bottom) |
|:----------------:|:-------------:|:--------------:|:-------------:|:----------------:|
| Dims (H x W x C) |  7 x 7 x 2048 | 14 x 14 x 1024 | 28 x 28 x 512 |   56 x 56 x 256  |
|    Total dims    |      100k     |      200k      |      400k     |       800k       |
|   Spatial dims   |     7 x 7     |     14 x 14    |    28 x 28    |      56 x 56     |

From layer 4 (top) to layer 1 (bottom), spatial dimensions increases (7x7 -> 56x56).
And total feature dimensions are also increases ( 100k -> 800k).

So, we divided loss to compensate this imbalance in feature dims.
i.e. 
layer 4 : x 1
layer 3 : x 1 / 2
layer 2 : x 1 / 4
layer 1 : x 1 / 8

I hope this additional explanation helped you understand my intentions in that parts.

**Comment by Ernie1** [comment]
Oh, I understand. Thanks for your careful explanation!
