### ISSUE TITLE
A question about Experimental results

### ISSUE THREAD

**Issue by baek85** [clovaai/overhaul-distillation#9]
First, thank you for release your code.

I'm wondering about your experimental results.
First, reported distillation models' classification accuracy is the final checkpoint's accuracy or best model's accuracy?

Second, how similar the results are when running the experiment multiple times?

**Comment by bhheo** [comment]
Hi

Here is details about reported performance.
- For CIFAR-100, we conducted 5-times training. And median accuracy over 5 final models was reported.
- For ImageNet and detection, performance of best model was reported.
- For segmentation, performance of final model was reported.

In case of performance variance, I don't have results over multiple time now.
So, I cannot tell the exact numbers. I'm sorry for that.
In my experience, the performance variance of distillation is similar to that of training a network with a baseline.
